[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Evolution of Language and Music computer labs"
authors = [{name = "CLClab", email = "w.h.zuidema@uva.nl"}]
dynamic = ["version", "description"]